<?php

namespace TradingPlatform\Domain\Strategy\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class StrategyConfiguration
 *
 * Represents a specific parameter configuration for a trading strategy.
 * Stores hyperparameter values, tracks performance through backtests,
 * and maintains relationships to parent strategies and optimization runs.
 *
 * **Configuration Sources:**
 * - 'manual': Hand-crafted by trader
 * - 'optimization': Generated by genetic algorithm
 * - 'variation': Modified from existing configuration
 * - 'default': Strategy default parameters
 *
 * **Lifecycle:**
 * 1. Create configuration with hyperparameters
 * 2. Run backtests to evaluate performance
 * 3. Mark as favorite if performs well
 * 4. Create variations for fine-tuning
 * 5. Deploy for live trading
 *
 * **Key Features:**
 * - Hyperparameter storage (JSON)
 * - DNA encoding for optimization
 * - Parent-child relationships for variations
 * - Soft deletes for historical tracking
 * - Favorite marking for quick access
 *
 * @author  Trading Platform Team
 *
 * @version 1.0.0
 *
 * @example Creating a manual configuration
 * ```php
 * $config = StrategyConfiguration::create([
 *     'strategy_id' => 1,
 *     'name' => 'RSI 14/30/70 - Conservative',
 *     'hyperparameters' => [
 *         'period' => 14,
 *         'oversold' => 30,
 *         'overbought' => 70,
 *     ],
 *     'source' => 'manual',
 *     'is_favorite' => false,
 *     'notes' => 'Conservative thresholds for low-volatility markets',
 * ]);
 * ```
 * @example Creating from optimization
 * ```php
 * $optimizedConfig = StrategyConfiguration::create([
 *     'strategy_id' => 1,
 *     'name' => 'RSI Optimized Gen50',
 *     'hyperparameters' => ['period' => 11, 'oversold' => 25, 'overbought' => 75],
 *     'dna' => '11_25_75',
 *     'source' => 'optimization',
 *     'optimization_run_id' => 42,
 * ]);
 * ```
 */
class StrategyConfiguration extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'strategy_id',
        'name',
        'hyperparameters',
        'dna',
        'source',
        'optimization_run_id',
        'parent_config_id',
        'is_favorite',
        'notes',
    ];

    protected $casts = [
        'hyperparameters' => 'array',
        'is_favorite' => 'boolean',
    ];

    /**
     * Get the strategy this configuration belongs to
     */
    public function strategy(): BelongsTo
    {
        return $this->belongsTo(Strategy::class);
    }

    /**
     * Get the optimization run that created this configuration
     */
    public function optimizationRun(): BelongsTo
    {
        return $this->belongsTo(OptimizationRun::class);
    }

    /**
     * Get the parent configuration (if this is a variation)
     */
    public function parentConfig(): BelongsTo
    {
        return $this->belongsTo(StrategyConfiguration::class, 'parent_config_id');
    }

    /**
     * Get child configurations (variations)
     */
    public function childConfigs(): HasMany
    {
        return $this->hasMany(StrategyConfiguration::class, 'parent_config_id');
    }

    /**
     * Get backtest results for this configuration
     */
    public function backtestResults(): HasMany
    {
        return $this->hasMany(BacktestResult::class);
    }

    /**
     * Get optimization results for this configuration
     */
    public function optimizationResults(): HasMany
    {
        return $this->hasMany(OptimizationResult::class);
    }

    /**
     * Scope: Only favorites
     */
    public function scopeFavorites($query)
    {
        return $query->where('is_favorite', true);
    }

    /**
     * Scope: Filter by source
     */
    public function scopeSource($query, string $source)
    {
        return $query->where('source', $source);
    }

    /**
     * Scope: From optimization
     */
    public function scopeFromOptimization($query)
    {
        return $query->where('source', 'optimization');
    }

    /**
     * Get hyperparameter value
     */
    public function getHyperparameter(string $key, $default = null)
    {
        return $this->hyperparameters[$key] ?? $default;
    }

    /**
     * Set hyperparameter value
     */
    public function setHyperparameter(string $key, $value): void
    {
        $params = $this->hyperparameters;
        $params[$key] = $value;
        $this->hyperparameters = $params;
    }

    /**
     * Get best backtest result
     */
    public function getBestBacktestResult()
    {
        return $this->backtestResults()
            ->orderBy('sharpe_ratio', 'desc')
            ->first();
    }
}
