<?php

namespace TradingPlatform\Domain\Strategy;

/**
 * Class Signal
 *
 * Represents an actionable trading signal generated by a strategy.
 * Contains all information needed to execute a trade including entry price,
 * quantity, risk controls (stop loss, take profit), and metadata for tracking.
 *
 * **Signal Types:**
 * - BUY: Long position signal
 * - SELL: Short position or exit long signal
 * - HOLD: No action required
 *
 * **Components:**
 * - Entry: instrumentId, action, price, quantity
 * - Risk Controls: stopLoss, takeProfit
 * - Metadata: strategyName, confidence, indicators, etc.
 *
 * **Use Cases:**
 * - Strategy signal generation
 * - Order placement automation
 * - Backtesting trade simulation
 * - Signal performance tracking
 * - Risk management integration
 *
 * @author  Trading Platform Team
 *
 * @version 1.0.0
 *
 * @example Creating a BUY signal with risk controls
 * ```php
 * $signal = new Signal(
 *     instrumentId: 'RELIANCE',
 *     action: Signal::BUY,
 *     price: 2510.50,
 *     quantity: 100,
 *     strategyName: 'RSI_Momentum',
 *     stopLoss: 2450.00,      // 2.4% stop loss
 *     takeProfit: 2600.00,    // 3.6% take profit
 *     metadata: [
 *         'rsi' => 28.5,
 *         'confidence' => 0.85,
 *         'timeframe' => '15m',
 *     ]
 * );
 * ```
 * @example SELL signal for short position
 * ```php
 * $signal = new Signal(
 *     instrumentId: 'NIFTY50_FUT',
 *     action: Signal::SELL,
 *     price: 19500.00,
 *     quantity: 50,
 *     strategyName: 'Breakdown_Strategy',
 *     stopLoss: 19650.00,     // Stop above resistance
 *     takeProfit: 19200.00,   // Target support level
 * );
 * ```
 */
class Signal
{
    public const BUY = 'BUY';

    public const SELL = 'SELL';

    public const HOLD = 'HOLD';

    public string $instrumentId;

    public string $action;

    public float $price;

    public int $quantity;

    public ?float $stopLoss;

    public ?float $takeProfit;

    public string $strategyName;

    public array $metadata;

    public function __construct(
        string $instrumentId,
        string $action,
        float $price,
        int $quantity,
        string $strategyName,
        ?float $stopLoss = null,
        ?float $takeProfit = null,
        array $metadata = []
    ) {
        $this->instrumentId = $instrumentId;
        $this->action = $action;
        $this->price = $price;
        $this->quantity = $quantity;
        $this->strategyName = $strategyName;
        $this->stopLoss = $stopLoss;
        $this->takeProfit = $takeProfit;
        $this->metadata = $metadata;
    }
}
